version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www
      - /var/www/vendor
    depends_on:
      - db

  scheduler:
    build: .
    container_name: laravel_scheduler
    volumes:
      - .:/var/www
      - /var/www/vendor
    command: php artisan schedule:work
    depends_on:
      - app

  webserver:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"